packages:
  - "apps/*"
  - "scripts/*"

verifyDepsBeforeRun: false

allowBuilds:
  esbuild: false
  sharp: false

onlyBuiltDependencies:
  - esbuild
  - "@tailwindcss/oxide"
  - sharp
  - better-sqlite3
